# Generated by Django 5.2.6 on 2025-11-09 16:56

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="The actual code (e.g., 'SUMMER10')", max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_type', models.CharField(choices=[('P', 'Percentage'), ('F', 'Fixed Amount')], default='P', max_length=1)),
                ('value', models.DecimalField(decimal_places=2, help_text='The value (e.g., 10.00 for 10% or $10.00 fixed)', max_digits=5)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Maximum total times the code can be used (0 for unlimited)')),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('min_fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum fare required to use this code', max_digits=6)),
            ],
            options={
                'verbose_name': 'Discount Code',
                'verbose_name_plural': 'Discount Codes',
            },
        ),
    ]
