# Generated by Django 5.2.6 on 2025-12-06 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount_codes', '0001_initial'),
        ('user', '0020_rename_rider_passenger_alter_customuser_trikego_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='cost',
            field=models.PositiveIntegerField(default=0, help_text='Number of loyalty points required to redeem this code'),
        ),
        migrations.CreateModel(
            name='LoyaltyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.PositiveIntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='discount_codes.discountcode')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='user.passenger')),
            ],
            options={
                'verbose_name': 'Loyalty Redemption',
                'verbose_name_plural': 'Loyalty Redemptions',
                'unique_together': {('passenger', 'discount_code')},
            },
        ),
    ]
