# Generated by Django 5.2.6 on 2025-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_tricycle_cr_image_url_tricycle_mtop_image_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rider',
            new_name='Passenger',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='trikego_user',
            field=models.CharField(choices=[('P', 'Passenger'), ('A', 'Admin'), ('D', 'Driver')], default='P', max_length=1),
        ),
    ]
