# Generated by Django 5.2.6 on 2025-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_tricycle_cr_image_url_tricycle_mtop_image_url_and_more'),
    ]

    operations = [
        # Migration removed: model already created as 'Passenger' in earlier migrations after refactor.
    ]
