# Generated by Django 5.2.6 on 2025-11-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_pin_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of failed PIN verification attempts'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_pin_created_at',
            field=models.DateTimeField(blank=True, help_text='When the PIN was generated', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_pin_expires_at',
            field=models.DateTimeField(blank=True, help_text='PIN expiry time (5 minutes)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_pin_hash',
            field=models.CharField(blank=True, help_text='Hashed 4-digit PIN for cash payment verification', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_pin_max_attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum allowed PIN attempts'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Whether cash payment has been verified via PIN'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When payment was verified', null=True),
        ),
    ]
