# Generated by Django 5.2.6 on 2025-11-03 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_create_rating_table'),
        ('booking', '0012_create_driverlocation_and_routesnapshot'),
    ]

    operations = [
    ]
