# Generated by Django 5.2.6 on 2025-11-29 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_booking_discount_amount_booking_discount_code_and_more'),
        ('discount_codes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_boo_rider_i_eb21d8_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rider',
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(blank=True, limit_choices_to={'trikego_user': 'P'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Driver Assignment'), ('accepted', 'Driver Accepted'), ('on_the_way', 'Driver On The Way'), ('started', 'Trip Started'), ('completed', 'Completed'), ('cancelled_by_passenger', 'Cancelled by Passenger'), ('cancelled_by_driver', 'Cancelled by Driver'), ('no_driver_found', 'No Driver Found')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='bookingstop',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('CURRENT', 'Current'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=30),
        ),
        migrations.AlterField(
            model_name='ratingandfeedback',
            name='rater',
            field=models.ForeignKey(limit_choices_to={'trikego_user': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Rater (Passenger)'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['passenger'], name='booking_boo_passeng_ebb46f_idx'),
        ),
    ]
