# Generated by Django 5.2.6 on 2025-11-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notificatio_user_id_1159a5_idx',
            old_name='notif_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notificatio_is_acti_12dfb9_idx',
            old_name='notif_active_idx',
        ),
    ]
